version: '3.7'
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5673:15672"

  redis:
      image: redis
      volumes:
        - "redis:/data"
      ports:
        - 6379:6379

  worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery -A app.tasks.send_email worker --loglevel=DEBUG -c 1

  flower:
    build:
      context: backend
      dockerfile: Dockerfile
    command: flower --broker=amqp://admin:mypass@rabbit:5672 --broker_api=http://admin:mypass@rabbit:15672/api/ --port=5555
    ports:
        - 5555:5555
    depends_on:
      - "redis"
      - "rabbit"
      - "worker"

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 1234@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_LISTEN_PORT: 5050
    depends_on:
      - postgres
    ports:
      - "5050:5050"
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: always

  backend:
    build:
      context: backend      
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
    ports:
      - 8000:8000
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://postgres:postgrespassword@postgres:5432/app'
      FIRST_SUPERUSER: 'superuser@admin.com'
      FIRST_SUPERUSER_PASSWORD: 'superuserpassword'
    depends_on:
      - "postgres"

volumes:
  db-data:
  pgadmin:
  redis: