from os import getenv


PROJECT_NAME = "debito_automatico"

SQLALCHEMY_DATABASE_URI = getenv("DATABASE_URL")

API_V1_STR = "/api/v1"

FIRST_SUPERUSER = getenv("FIRST_SUPERUSER")
FIRST_SUPERUSER_PASSWORD = getenv("FIRST_SUPERUSER_PASSWORD")
